#!/bin/bash
# --------------------------------------------------------------------------------
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# --------------------------------------------------------------------------------

# Build a self-extracting .run installer for the PTOAS install tree.
#
# The produced archive is a plain POSIX shell script with a gzip tarball
# appended after a marker line. When executed with --full it extracts the
# payload under <install-path> and with --uninstall it removes the previously
# installed directory. This mirrors the interface the CANN smoke pipeline's
# pto-as_compile.sh drives (build_out/*.run --full / --uninstall) without
# depending on the closed-source makeself tooling.
#
# Usage:
#   make_ptoas_run.sh <package_root> <payload_dir> <output_run> \
#       [<version>] [<package_name>]

set -euo pipefail

if [ $# -lt 3 ]; then
  echo "Usage: $0 <package_root> <payload_dir> <output_run> [<version>] [<package_name>]" >&2
  exit 1
fi

PACKAGE_ROOT="$(cd "$1" && pwd -P)"
PAYLOAD_DIR="$(cd "$2" && pwd -P)"
OUTPUT_RUN="$3"
VERSION="${4:-0.57}"
PACKAGE_NAME="${5:-ptoas}"

[[ -d "${PAYLOAD_DIR}" ]] || {
  echo "Error: payload dir not found: ${PAYLOAD_DIR}" >&2
  exit 1
}

mkdir -p "$(dirname "${OUTPUT_RUN}")"
rm -f "${OUTPUT_RUN}"

STUB_FILE="$(mktemp)"
trap 'rm -f "${STUB_FILE}"' EXIT

cat > "${STUB_FILE}" <<'STUB'
#!/bin/bash
#
# PTOAS self-extracting installer generated by make_ptoas_run.sh.
#

VERSION="@VERSION_AT_PACKAGE_TIME@"
PACKAGE="@PACKAGE_NAME_AT_PACKAGE_TIME@"

usage() {
  echo "Usage: $0 [--full|--install] [--uninstall] [--check] [--help] [--install-path=<dir>]"
  echo "  --full, --install    Extract the package contents under <install-path>"
  echo "  --uninstall          Remove files installed by this package"
  echo "  --check              Verify the archive payload integrity"
  echo "  --install-path=<dir> Target installation directory (default: /usr/local/Ascend/${PACKAGE}-${VERSION})"
  echo "  --help               Show this help"
  echo
  echo "Examples:"
  echo "  $0 --full --install-path=/opt/ptoas"
  echo "  $0 --uninstall --install-path=/opt/ptoas"
}

INSTALL_PATH=""
ACTION=""

for arg in "$@"; do
  case "${arg}" in
    --full|--install)
      ACTION="install"
      ;;
    --uninstall)
      ACTION="uninstall"
      ;;
    --check|--verify)
      ACTION="check"
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    --install-path=*)
      INSTALL_PATH="${arg#--install-path=}"
      ;;
    *)
      echo "Warning: ignoring unknown argument: ${arg}" >&2
      ;;
  esac
done

[ -z "${INSTALL_PATH}" ] && INSTALL_PATH="/usr/local/Ascend/${PACKAGE}-${VERSION}"

echo "PTOAS ${VERSION} (${PACKAGE})"
echo "Install path: ${INSTALL_PATH}"
echo "Action: ${ACTION:-check}"

# Locate the inline payload: it starts after the ARCHIVE_MARKER line.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_NAME="$(basename "${BASH_SOURCE[0]}")"
PAYLOAD_START="$(awk '/^#__PTOAS_ARCHIVE_MARKER__$/ { print NR + 1; exit }' "${SCRIPT_DIR}/${SCRIPT_NAME}")"

if [ -z "${PAYLOAD_START}" ]; then
  echo "ERROR: archive payload marker not found" >&2
  exit 1
fi

case "${ACTION}" in
  install)
    if [ -e "${INSTALL_PATH}" ]; then
      # Never clobber an existing install without explicit approval; echo y
      # from the CI pipeline answers this prompt.
      echo "Target directory exists: ${INSTALL_PATH}"
      echo "Continuing: files will be overwritten."
    fi
    if ! mkdir -p "${INSTALL_PATH}"; then
      echo "ERROR: failed to create install directory ${INSTALL_PATH}" >&2
      exit 1
    fi
    if ! tail -n +"${PAYLOAD_START}" "${SCRIPT_DIR}/${SCRIPT_NAME}" | tar xzf - -C "${INSTALL_PATH}"; then
      echo "ERROR: extraction failed" >&2
      exit 1
    fi
    echo "Install succeeded: ${INSTALL_PATH}"
    ;;
  uninstall)
    if ! mkdir -p "${INSTALL_PATH}"; then
      echo "ERROR: failed to access install directory ${INSTALL_PATH}" >&2
      exit 1
    fi
    if ! rm -rf "${INSTALL_PATH}"; then
      echo "ERROR: failed to remove ${INSTALL_PATH}" >&2
      exit 1
    fi
    echo "Uninstall succeeded: ${INSTALL_PATH} removed"
    ;;
  check|*)
    if tail -n +"${PAYLOAD_START}" "${SCRIPT_DIR}/${SCRIPT_NAME}" | tar tzf - >/dev/null; then
      echo "Payload OK"
    else
      echo "ERROR: payload integrity check failed" >&2
      exit 1
    fi
    ;;
esac

exit 0
STUB

# Substitute placeholders.
sed -i "s|@VERSION_AT_PACKAGE_TIME@|${VERSION}|g; s|@PACKAGE_NAME_AT_PACKAGE_TIME@|${PACKAGE_NAME}|g" "${STUB_FILE}"

# Assemble: stub + marker + gzipped tarball of the payload.
cp "${STUB_FILE}" "${OUTPUT_RUN}"
echo "#__PTOAS_ARCHIVE_MARKER__" >> "${OUTPUT_RUN}"
(
  cd "${PAYLOAD_DIR}"
  tar czf - .
) >> "${OUTPUT_RUN}"

# Explicit 755: the OBS uploader opens the artifact from the host workspace as
# a non-root user; a 711 mode (execute only) makes that open fail with "File
# does not exist". Keep read permission for group/other.
chmod 755 "${OUTPUT_RUN}"

echo "Built ${OUTPUT_RUN} ($(du -h "${OUTPUT_RUN}" | cut -f1))"